associating podcast with episode
factly/dega-server pull request #237
Opened 2021-04-20 07:25 UTC by Bhumi101097

Associating podcast with episode
Closes #211

2021-04-20 19:15 UTC, hetjagani commented
We should remove Episodes[] from Podcast model. And please refer to `fix/podcasts` branch, I have fixed some things in podcast and episode methods.

2021-04-21 05:53 UTC, shreeharsha-factly requested changes

2021-04-21 05:53 UTC, shreeharsha-factly commented on service/podcast/action/episode/route.go
> +	PodcastID     uint           `json:"podcast_id" validate:"required"`
PodcastID is not a mandatory field

2021-04-21 17:54 UTC, hetjagani commented
Changed route from `/podcast/podcasts` to `/podcast` for Podcasts.

2021-04-21 19:43 UTC, shreeharsha-factly approved these changes

2021-04-21 19:43 UTC, merged