Used gorm hooks to validate for same space.
factly/dega-server pull request #63
Opened 2020-08-13 06:40 UTC by hetjagani

2020-08-13 08:26 UTC, dmonark requested changes

2020-08-13 08:26 UTC, dmonark commented on service/core/action/post/update.go
> +		tx.Model(&result.Post).Association("Tags").Delete(oldTags)
add err and rollback

2020-08-13 08:26 UTC, dmonark commented on service/core/action/post/update.go
> +		tx.Model(&result.Post).Association("Categories").Delete(oldCategories)
add err and rollback

2020-08-17 06:10 UTC, dmonark approved these changes

2020-08-17 06:13 UTC, shreeharsha-factly approved these changes

2020-08-17 06:38 UTC, merged